# Generated by Django 2.2.5 on 2021-06-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='url',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
