# Generated by Django 2.2.5 on 2021-06-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_fname', models.CharField(max_length=30)),
                ('guest_lname', models.CharField(max_length=30)),
                ('guest_phone', models.CharField(max_length=20)),
                ('guest_country', models.CharField(max_length=30)),
                ('guest_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField(default=0)),
                ('room_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingmgmt.Room_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('is_cancelled', models.BooleanField(blank=True)),
                ('cancellation_date', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingmgmt.Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingmgmt.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minibar', models.BooleanField(blank=True)),
                ('room_service', models.BooleanField(blank=True)),
                ('early_checkIn', models.BooleanField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingmgmt.Reservation')),
            ],
        ),
    ]
